export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR';
export const LIST_CALENDAR_EVENT = 'LIST_CALENDAR_EVENT';
export const LIST_REPOSITORIES = 'LIST_REPOSITORIES';
